config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  get '/tasks', to: 'tasks#index', as: 'tasks'
  get '/tasks/new', to: 'tasks#new'
  post '/tasks', to: 'tasks#create'
  patch '/tasks/:id', to: 'tasks#update'
  delete '/tasks/:id', to: 'tasks#destroy'
  get '/tasks/:id', to: 'tasks#show', as: 'task'
  get '/tasks/:id/edit', to: 'tasks#edit', as: 'edit_task'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)  #if update is successful redirects to tasks/show
      redirect_to @task
    else
      render 'edit'  #if not successful it will go back to edit
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  def show
    @task = Task.find(params[:id])
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit A Task</h1>

<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_area :details %>

  <%= f.label :completed %>
  <%= f.check_box :completed %>

  <%= f.submit %>
<% end %>

app/views/tasks/index.html.erb
<h1> All Tasks </h1>

<% @tasks.each do |task| %>
  <ul>
    <li><%=link_to task.title, task_path(task) %></li>
    <p>Details: <%= task.details %></p>
    <p>Done: <%= task.completed %></p>
    <p><%= link_to 'Edit', edit_task_path(task) %></p>
  </ul>
<% end %>
  <%= link_to 'Create a New Task', tasks_new_path %>

app/views/tasks/new.html.erb
<h1>Add A Task</h1>

<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_area :details %>

  <%= f.label :completed %>
  <%= f.check_box :completed %>

  <%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.title %></h1>
<p>Details: <%= @task.details %></p>
<p>Done? :<%= @task.completed %></p>
<%= link_to 'Edit', edit_task_path(@task) %>
<%= link_to 'Back', tasks_path(@tasks) %>
<%= link_to  "Delete", task_path(@task), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>